# Generated by Django 4.0.8 on 2022-11-04 04:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('password_reset', models.CharField(max_length=50, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=0)),
                ('is_staff', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'api_account',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('file', models.FileField(default='Docs/None/No-doc.pdf', upload_to='Docs/')),
                ('img', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
        ),
    ]
