# Generated by Django 4.0.8 on 2022-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_is_saved_event_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='references',
            field=models.CharField(choices=[('I', 'Instagram'), ('F', 'facebook'), ('W', 'Whatsapp'), ('T', 'twitter'), ('T', 'tv'), ('O', 'other')], default='OTHER', max_length=12),
            preserve_default=False,
        ),
    ]
