# Generated by Django 4.0.8 on 2022-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_pagereadlogs_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereadlogs',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
