# Generated by Django 4.0.8 on 2022-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pagereadlogs_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagereadlogs',
            name='page',
            field=models.IntegerField(null=True),
        ),
    ]
