# Generated by Django 4.0.8 on 2022-11-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_pagereadlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageReadLogs',
        ),
    ]
