# Generated by Django 4.0.8 on 2022-11-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_pagereadlogs_page'),
        ('review', '0003_delete_pagereadlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreviewlogs',
            old_name='status',
            new_name='status_before',
        ),
        migrations.AddField(
            model_name='eventreviewlogs',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blog.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventreviewlogs',
            name='status_now',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('U', 'Under Review'), ('S', 'Submitted'), ('RS', 'Resubmitted'), ('RW', 'Rework')], default='U', max_length=10),
        ),
    ]
