# Generated by Django 4.0.8 on 2022-11-11 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_event_other_remove_event_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0004_rename_status_eventreviewlogs_status_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreviewlogs',
            old_name='status_before',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='eventreviewlogs',
            name='status_now',
        ),
        migrations.CreateModel(
            name='EventContentWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_content_writer_id', models.ForeignKey(db_column='assigned_content_writer_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_writers', to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_writer', to='blog.event')),
            ],
        ),
    ]
